tap "homebrew/cask"

brew "openjdk"
brew "node"
brew "ffmpeg"
brew "imagemagick"

cask "visual-studio-code"
cask "intellij-idea-ce"

cask "google-chrome"
cask "firefox"
cask "discord"

cask 'streamlabs-obs'
