tap "homebrew/cask"

brew "openjdk"
brew "node"
brew "deno"
brew "ffmpeg"
brew "imagemagick"
brew "librsvg"
brew "jq"

cask "visual-studio-code"
cask "intellij-idea-ce"
cask "android-studio"
cask "insomnia"
cask "dbeaver-community"
cask "krita"
cask "inkscape"
cask "docker"

cask "google-chrome"
cask "firefox"
cask "discord"
cask "obsidian"

cask 'streamlabs-obs'
